name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.8"]
        os: ["ubuntu-24.04"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Include ppa repository
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          sudo apt-get install python${{ matrix.python-version }}-dev
          sudo update-alternatives --install /usr/bin/python3 python3 `which python${{ matrix.python-version }}` 1
          sudo update-alternatives --install /usr/bin/python3-config python3-config `which python${{ matrix.python-version }}-config` 1
      - name: Build
        run: make

      - name: Generate release file
        run: echo ${{ github.sha }} > Release.txt
        
      - name: Zip
        uses: montudor/action-zip@v1
        with: 
          args: zip -qq -r release.zip bin/minqlx.zip bin/minqlx.x64.so bin/run_server_x64_minqlx.sh bin/run_server_x86_minqlx.sh
        
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release.zip
            Release.txt
