name: Makefile CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install python
      run: |
        add-apt-repository ppa:deadsnakes/ppa \
        apt-get update -y \
        apt-get -y install python3.8 python3.8-dev python3.8-distutils \
        rm /usr/bin/python3 \
        ln -s /usr/bin/python3.8 /usr/bin/python3 \
        ln -s /usr/bin/python3.8-config /usr/bin/python3-config

    - uses: actions/checkout@v4

    - name: archive release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'minqlx-latest.zip'
        path: 'bin\*'
